//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoWebApiCliente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int IDCLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> CPOSTAL { get; set; }
        public string EMAIL { get; set; }
    }
}
